language: ruby
rvm:
 - 2.3
services:
  - postgresql

before_script:
  - psql -c 'create database sous_chef_test;' -U postgres

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

addons:
  firefox: "46.0"